### ISSUE TITLE
Schematics for new version 1.5

### ISSUE THREAD

**Issue by rei-vilo** [bbcmicrobit/hardware#3] opened 2019-02-06 08:41 UTC
Schematics are for previous version 1.3 while current version is 1.5. 

Please provide the schematics for current version 1.5. 

See [micro:bit motion sensor hardware change](
https://support.microbit.org/support/solutions/articles/19000087020-micro-bit-motion-sensor-hardware-change). 

Thank you!

**Comment by microbit-pauline** [comment] 2019-02-06 10:01
I think that Mark also got a support request, not sure if its the same person

**Comment by microbit-carlos** [comment] 2019-02-06 10:53
Hi @rei-vilo,
Thanks for bringing this to our attention. Due to the nature of the micro:bit design being done in partnership with other organisations we are currently working internally to ensure we do everything required to be able release the v1.5 schematics.
It might be a slow process, but this is high in our priority list, so as soon as we can publish the schematics we'll update this repository.

**Comment by rei-vilo** [comment] 2019-02-06 10:59
Thank you! 

Actually, I've found what I was looking for. 

The exact reference of the motion sensor on the version 1.5 of the board is a 3-axis [LSM303AGR](https://www.st.com/en/mems-and-sensors/lsm303agr.html) magnetometer and accelerometer.

**Comment by whaleygeek** [comment] 2019-05-22 08:10
You can also find up to date details about sensors and things like that on the tech pages - the images have been updated on those pages and the annotations show the new sensor part number

https://tech.microbit.org/hardware/

![Screen Shot 2019-05-22 at 09 09 59](https://user-images.githubusercontent.com/4086785/58157999-6fc76d00-7c71-11e9-8237-86121073bd72.png)


There is also a link further down on that page under the Motion Sensor heading, to the manufacturers data sheet.

https://www.st.com/en/mems-and-sensors/lsm303agr.html

**Comment by iwtfnsc** [comment] 2019-10-01 03:17
i have a question for microbit?
can i use microbit Schematics for my own design?

**Comment by iwtfnsc** [comment] 2019-10-01 10:44
Duplicate of #[1.5.pdf](url)

**Comment by iwtfnsc** [comment] 2019-10-01 10:54
[1.5.pdf](https://github.com/bbcmicrobit/hardware/files/3675800/1.5.pdf)
this is my design  ,reference 1,3,  please cheeck this Schematics,thanks .

**Comment by WestfW** [comment] 2020-01-30 09:56
Poke:  It's nearly a year after the initial request, and still no official 1.5 schematics?

**Comment by wangpengli** [comment] 2020-02-02 11:21
seems they forgot it.

**Comment by whaleygeek** [comment] 2020-02-02 15:20
The schematics are (c) BBC, so I guess they will have to provide them. @jaustin any thoughts?

**Comment by wangpengli** [comment] 2020-02-03 10:51
so long time passed.

David Whale <notifications@github.com> 于2020年2月2日周日 下午11:20写道：

**Comment by zfm076** [comment] 2020-03-20 09:22
So long time passed too.

**Closed as completed** 2020-08-07 09:49 UTC
